name: Tests

on:
  workflow_dispatch:
  push:
  pull_request:
#  schedule:
#    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.0, 8.1]
        stability: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, intl-68.1
          coverage: none
        env:
            fail-fast: true

      - name: Set up Docker
        run: |
          sudo rm /usr/local/bin/docker-compose
          curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > docker-compose
          chmod +x docker-compose
          sudo mv docker-compose /usr/local/bin

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

#      - name: Run PHP CS Fixer
#        if: ${{ matrix.php != 8.0 || matrix.php != 8.1 }}
#        run: composer run test:style

      - name: Execute tests
        run: |
            composer config --global process-timeout 2000
            sudo composer run test:unit
